# Site settings
title: Maude the Code Toad
blogger: Maude Lemaire
email: maude.codes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The adventures of Maude in the world of tech: documenting the good, the bad and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maudethecodetoad.com" # the base hostname & protocol for your site
twitter_username: qcmaude
github_username:  qcmaude

# Build settings
markdown: kramdown
